# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomMessageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtGui, QtWidgets
from ORM.Common.Styles import *
from SysManager.Images_res_rc import *


class Ui_CustomMessageDialog(object):
    def setupUi(self, CustomMessageDialog):
        CustomMessageDialog.setObjectName("CustomMessageDialog")
        CustomMessageDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        CustomMessageDialog.resize(700, 420)
        CustomMessageDialog.setMinimumSize(QtCore.QSize(700, 420))
        CustomMessageDialog.setMaximumSize(QtCore.QSize(700, 420))
        CustomMessageDialog.setBaseSize(QtCore.QSize(700, 420))
        CustomMessageDialog.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowMinMaxButtonsHint |
                                           QtCore.Qt.MSWindowsFixedSizeDialogHint | QtCore.Qt.WindowCloseButtonHint)
        self.gridLayoutWidget = QtWidgets.QWidget(CustomMessageDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 2, 681, 411))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LBL_Title = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.LBL_Title.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(message_dialog_image_style('logo.ico'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        CustomMessageDialog.setWindowIcon(icon)
        self.LBL_Title.setAlignment(QtCore.Qt.AlignCenter)
        self.LBL_Title.setObjectName("LBL_Title")
        self.verticalLayout.addWidget(self.LBL_Title)
        self.HLO_Message = QtWidgets.QHBoxLayout()
        self.HLO_Message.setSpacing(6)
        self.HLO_Message.setObjectName("HLO_Message")
        spacerItem = QtWidgets.QSpacerItem(40, 290, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLO_Message.addItem(spacerItem)
        self.VLO_Message = QtWidgets.QVBoxLayout()
        self.VLO_Message.setSpacing(6)
        self.VLO_Message.setObjectName("VLO_Message")
        self.LBL_Message_Image = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LBL_Message_Image.setMinimumSize(QtCore.QSize(96, 96))
        self.LBL_Message_Image.setMaximumSize(QtCore.QSize(96, 96))
        self.LBL_Message_Image.setBaseSize(QtCore.QSize(96, 96))
        self.LBL_Message_Image.setText("")
        self.LBL_Message_Image.setPixmap(message_dialog_image_style())
        self.LBL_Message_Image.setScaledContents(True)
        self.LBL_Message_Image.setAlignment(QtCore.Qt.AlignCenter)
        self.LBL_Message_Image.setObjectName("LBL_Message_Image")
        self.VLO_Message.addWidget(self.LBL_Message_Image)
        spacerItem1 = QtWidgets.QSpacerItem(20, 154, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.VLO_Message.addItem(spacerItem1)
        self.HLO_Message.addLayout(self.VLO_Message)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLO_Message.addItem(spacerItem2)
        self.LBL_Message = QtWidgets.QLabel(self.gridLayoutWidget)
        self.LBL_Message.setMinimumSize(QtCore.QSize(480, 220))
        self.LBL_Message.setMaximumSize(QtCore.QSize(480, 220))
        self.LBL_Message.setBaseSize(QtCore.QSize(480, 220))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.LBL_Message.setFont(font)
        self.LBL_Message.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.LBL_Message.setScaledContents(True)
        self.LBL_Message.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.LBL_Message.setWordWrap(True)
        self.LBL_Message.setObjectName("LBL_Message")
        self.HLO_Message.addWidget(self.LBL_Message)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLO_Message.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.HLO_Message)
        self.HLO_Button = QtWidgets.QHBoxLayout()
        self.HLO_Button.setSpacing(6)
        self.HLO_Button.setObjectName("HLO_Button")
        spacerItem4 = QtWidgets.QSpacerItem(40, 80, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLO_Button.addItem(spacerItem4)
        self.PBTN_Submit = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PBTN_Submit.setFont(font)
        self.PBTN_Submit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PBTN_Submit.setObjectName("PBTN_Submit")
        self.HLO_Button.addWidget(self.PBTN_Submit)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLO_Button.addItem(spacerItem5)
        self.PBTN_Reset = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PBTN_Reset.setFont(font)
        self.PBTN_Reset.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PBTN_Reset.setObjectName("PBTN_Reset")
        self.HLO_Button.addWidget(self.PBTN_Reset)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLO_Button.addItem(spacerItem6)
        self.PBTN_Close = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PBTN_Close.setFont(font)
        self.PBTN_Close.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.PBTN_Close.setObjectName("PBTN_Close")
        self.HLO_Button.addWidget(self.PBTN_Close)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HLO_Button.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.HLO_Button)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)

        self.retranslateUi(CustomMessageDialog)
        QtCore.QMetaObject.connectSlotsByName(CustomMessageDialog)

    def retranslateUi(self, CustomMessageDialog):
        _translate = QtCore.QCoreApplication.translate
        CustomMessageDialog.setWindowTitle(_translate("CustomMessageDialog", "信息提示"))
        self.LBL_Title.setText(_translate("CustomMessageDialog", "操作提示信息"))
        self.LBL_Message.setText(_translate("CustomMessageDialog", "这里显示相关操作信息"))
        self.PBTN_Submit.setText(_translate("CustomMessageDialog", "提 交"))
        self.PBTN_Reset.setText(_translate("CustomMessageDialog", "重 置"))
        self.PBTN_Close.setText(_translate("CustomMessageDialog", "关 闭"))
